### PR TITLE
Bump Virtualization SDK to post release format on develop

### PR DESCRIPTION
**Pull request by jeffngo**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Version Change

## What is the current behavior?

Issue Number: 303

## What is the new behavior?

- Changed the Virtualization SDK version to post release format

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ankursarin — APPROVED** [review]

**Review by ankursarin — CHANGES_REQUESTED** [review]
I think the `tools` package is missing a version bump?
Did `bumpversion` skip changing that?

**Review by ravi-cm — COMMENTED** [review]
One more file is missing - tools/src/main/python/dlpx/virtualization/_internal/VERSION?

**Comment by jeffngo** [comment]
> I think the `tools` package is missing a version bump?
> Did `bumpversion` skip changing that?

Nope. I couldn't find a good way to bump the dev build from prod. Ended up bumping these versions manually on this PR. The correct way of doing this from a prod release format would be to run `bumpversion minor` which would bump `3.0.0` to `3.1.0.dev0`.

**Review by ravi-cm — APPROVED** [review]

**Review by nhlien93 — COMMENTED** [review]
Do we know for a fact that the next version will be a minor version bumb? or maybe this doesn't even matter because we can always change it?

**Comment by jeffngo** [comment]
> Do we know for a fact that the next version will be a minor version bumb? or maybe this doesn't even matter because we can always change it?

Yeah, we don't know for sure but given that we will be releasing a major version this month, it seems more likely that the next version is going to be a minor version. And if things ever change, we could always change it, of course.

**Review by ankursarin — APPROVED** [review]

**Pull request merged**
